export const $APP = {};
export const shadow$provide = {};
export const $jscomp = {};
shadow$provide[0]=function(x,u,v,A){v.exports=function(p){var q=String.prototype.split,t=/()??/.exec("")[1]===p;return function(l,e,n){if("[object RegExp]"!==Object.prototype.toString.call(e))return q.call(l,e,n);var k=[],h=(e.ignoreCase?"i":"")+(e.multiline?"m":"")+(e.extended?"x":"")+(e.sticky?"y":""),g=0;e=new RegExp(e.source,h+"g");var c,a;l+="";t||(c=new RegExp("^"+e.source+"$(?!\\s)",h));for(n=n===p?4294967295:n>>>0;a=e.exec(l);){h=a.index+a[0].length;if(h>g){k.push(l.slice(g,a.index));!t&&
1<a.length&&a[0].replace(c,function(){for(var y=1;y<arguments.length-2;y++)arguments[y]===p&&(a[y]=p)});1<a.length&&a.index<l.length&&Array.prototype.push.apply(k,a.slice(1));var b=a[0].length;g=h;if(k.length>=n)break}e.lastIndex===a.index&&e.lastIndex++}g===l.length?(b||!e.test(""))&&k.push(""):k.push(l.slice(g));return k.length>n?k.slice(0,n):k}}()};
shadow$provide[1]=function(x,u,v,A){var p=[].indexOf;v.exports=function(q,t){if(p)return q.indexOf(t);for(var l=0;l<q.length;++l)if(q[l]===t)return l;return-1}};
shadow$provide[2]=function(x,u,v,A){var p=u(1);v.exports=function(q){function t(c){var a=n();-1<p(a,c)||(a.push(c),k(a))}function l(c){var a=n();c=p(a,c);-1!==c&&(a.splice(c,1),k(a))}function e(c){return-1<p(n(),c)}function n(){for(var c=q.className.split(" "),a=[],b=0;b<c.length;b++)c[b]&&a.push(c[b]);return a}function k(c){var a=c.length;q.className=c.join(" ");g.length=a;for(var b=0;b<c.length;b++)g[b]=c[b];delete c[a]}var h=q.classList;if(h)return h;var g={add:t,remove:l,contains:e,toggle:function(c){if(e(c))return l(c),
!1;t(c);return!0},toString:function(){return q.className},length:0,item:function(c){return n()[c]||null}};return g}};
shadow$provide[3]=function(x,u,v,A){};
shadow$provide[4]=function(x,u,v,A){function p(){function k(){function g(b){function y(d){d=t(d,/([\.#]?[^\s#.]+)/);/^\.|#/.test(d[1])&&(a=e.createElement("div"));q(d,function(m){var z=m.substring(1,m.length);m&&(a?"."===m[0]?l(a).add(z):"#"===m[0]&&a.setAttribute("id",z):a=e.createElement(m))})}var r;if(null!=b)if("string"===typeof b)a?a.appendChild(r=e.createTextNode(b)):y(b);else if("number"===typeof b||"boolean"===typeof b||b instanceof Date||b instanceof RegExp)a.appendChild(r=e.createTextNode(b.toString()));
else if("[object Array]"==Object.prototype.toString.call(b))q(b,g);else if(b&&b.nodeName&&b.nodeType)a.appendChild(r=b);else if(b instanceof n)a.appendChild(r=b);else if("object"===typeof b)for(var f in b)if("function"===typeof b[f])/^on\w+/.test(f)?function(d,m){a.addEventListener?(a.addEventListener(d.substring(2),m[d],!1),h.push(function(){a.removeEventListener(d.substring(2),m[d],!1)})):(a.attachEvent(d,m[d]),h.push(function(){a.detachEvent(d,m[d])}))}(f,b):(a[f]=b[f](),h.push(b[f](function(d){a[f]=
d})));else if("style"===f)if("string"===typeof b[f])a.style.cssText=b[f];else for(var B in b[f])(function(d,m){if("function"===typeof m)a.style.setProperty(d,m()),h.push(m(function(C){a.style.setProperty(d,C)}));else var z=b[f][d].match(/(.*)\W+!important\W*$/);z?a.style.setProperty(d,z[1],"important"):a.style.setProperty(d,b[f][d])})(B,b[f][B]);else if("attrs"===f)for(var w in b[f])a.setAttribute(w,b[f][w]);else"data-"===f.substr(0,5)?a.setAttribute(f,b[f]):a[f]=b[f];else"function"===typeof b&&(w=
b(),a.appendChild(r=w&&w.nodeName&&w.nodeType?w:e.createTextNode(w)),h.push(b(function(d){d&&d.nodeName&&d.nodeType&&r.parentElement?(r.parentElement.replaceChild(d,r),r=d):r.textContent=d})));return r}for(var c=[].slice.call(arguments),a=null;c.length;)g(c.shift());return a}var h=[];k.cleanup=function(){for(var g=0;g<h.length;g++)h[g]();h.length=0};return k}function q(k,h){if(k.forEach)return k.forEach(h);for(var g=0;g<k.length;g++)h(k[g],g)}var t=u(0),l=u(2);x="undefined"===typeof window?u(3):window;
var e=x.document,n=x.Text;(v.exports=p()).context=p};
var t=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},v=function(a){return null!=a&&!1!==a},x=function(a,b){var c=null==b?null:b.constructor;return Error(["No protocol method ",a," defined for type ",v(v(c)?c.Pb:c)?c.pb:t(b),": ",b].join(""))},wa=function(){var a=ye;if(null!=a&&null!=a.gb)a=a.gb(a);else{var b=wa[t(null==a?null:a)];if(null!=b)a=b.g?b.g(a):b.call(null,a);else if(b=wa._,null!=b)a=b.g?b.g(a):b.call(null,a);else throw x("IDeref.-deref",a);}return a},
Ta=function(a){if(null!=a&&null!=a.wb)a.wb(a,!0);else{var b=Ta[t(null==a?null:a)];if(null!=b)b.h?b.h(a,!0):b.call(null,a,!0);else if(b=Ta._,null!=b)b.h?b.h(a,!0):b.call(null,a,!0);else throw x("IVolatile.-vreset!",a);}},Jc=function(){this.state=!1},ue=function(a){this.f=a;this.value=null},we=function(a){if(null!=a&&null!=a.zb)a=a.zb(a,null);else{var b=we[t(null==a?null:a)];if(null!=b)a=b.h?b.h(a,null):b.call(null,a,null);else if(b=we._,null!=b)a=b.h?b.h(a,null):b.call(null,a,null);else throw x("ICompletable.-resolve!",
a);}return a},xe=function(a,b,c){if(null!=a&&null!=a.Cb)a.Cb(a,b,c);else{var d=xe[t(null==a?null:a)];if(null!=d)d.j?d.j(a,b,c):d.call(null,a,b,c);else if(d=xe._,null!=d)d.j?d.j(a,b,c):d.call(null,a,b,c);else throw x("IScheduler.-schedule!",a);}},ze=function(a,b){var c=ye instanceof ue?wa():ye;xe(c,a,b)},Ae=function(a){this.state=a},Be=function(){},Ce=function(){return new Be},Ee=function(){var a={},b=new De(function(c,d){a.resolve=c;return a.reject=d});b.ec=F;b.zb=function(c,d){return a.resolve(d)};
b.fc=function(c,d){return a.reject(d)};return b},Fe=function(a){var b=Ee();ze(a,function(){return we(b)});return b},Le=function(a,b){var c=He[a];if(void 0!==c)return c;try{Ie.push(a);var d=Je[a],e=shadow$provide[a];if(void 0===d){if(void 0===e)throw"Module not provided: "+a;d={exports:{}};Je[a]=d}if(e){delete shadow$provide[a];try{e.call(d,Ke,Le,d,d.exports)}catch(h){throw console.warn("shadow-cljs - failed to load",a),h;}if(b){var g=b.globals;if(g)for(a=0;a<g.length;a++)window[g[a]]=d.exports}}}finally{Ie.pop()}return d.exports},
l=function(a){return new Promise(function(b,c){var d=new Image;(null!=d?d:{}).onload=function(){return b.g?b.g(d):b.call(null,d)};(null!=d?d:{}).onerror=c;c=null!=d?d:{};c.src=a;return c})},m=function(a){return"x y w h ax ay".split(" ").reduce(function(b,c){var d=a[c];if(v(d)){var e="--".concat(c);c=-1!=["x","y","w","h"].indexOf(c)?"px":null;b[e]=(null==d?null:d.constructor)==Number||parseFloat(d).toString()==d?"".concat(d,c):d}return b},{})},p=function(a,b){return l(a).then(function(c){var d={props:Object.assign({x:0,
y:0},b)};var e=null!=d&&"props"in d?d.props:void 0;e=m(e);c=null!=c&&"src"in c?c.src:void 0;c=n("img",{src:c,className:"twge-entity",style:e,entity:d});console.log("entity",d);(null!=d?d:{}).element=c;(null!=d?d:{}).set=Re.bind(null,d);(null!=d?d:{}).get=function(g){return d.props[g]};return d})};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var Ke=globalThis;var F={};Jc.prototype.wb=function(a,b){return this.state=b};Jc.prototype.gb=function(){return this.state};ue.prototype.gb=function(){v(this.f)&&(this.value=this.f.D?this.f.D():this.f.call(null),this.f=null);return this.value};var ye=new ue(function(){return Ce.D?Ce.D():Ce.call(null)});Be.prototype.Cb=function(a,b,c){var d=new Jc,e=setTimeout(function(){try{return c.D?c.D():c.call(null)}finally{Ta(d)}},b);return new Ae({done:d,cancelled:!1,"cancel-fn":function(){return clearTimeout(e)}})};var De=Promise;var Je={},He={},Ie=[];Le.cache={};Le.resolve=function(a){return a};var n;n=Le(4,{});var Re=function Re(a,b,c){if(v(c)){var e=a.props;e[b]=c;return Re.j?Re.j(a,e,null):Re.call(null,a,e,null)}c=n("img",{style:m(b)});c=null!=c&&"style"in c?c.style:void 0;c=null!=c&&"cssText"in c?c.cssText:void 0;e=null!=a?a:{};e=null!=e?e:{};e.props=Object.assign(e.props,b);return a.element.style=c},k=[];export default{}.dc;export const image=p;export const emoji=function(a,b){a=a.codePointAt.call(a,0);a=a.toString.call(a,16);return p("https://raw.githubusercontent.com/".concat("twitter/twemoji/master/assets/svg/",a,".svg"),b)};export const wait=function(a){return Fe(a)};export const frame=function(){return new Promise(function(a){var b=new Date;return requestAnimationFrame(function(){var c=null!=k&&"length"in k?k.length:void 0;c=k.splice(0,c);c=[new Date-b,c];return a.g?a.g(c):a.call(null,c)})})};
export const happened=function(a,b,c){a=a.filter(function(d){d=null!=d&&"code"in d?d.code:void 0;return d==b});a=v(c)?a.filter(function(d){d=null!=d&&"type"in d?d.type:void 0;return d==c}):a;a=null!=a&&"length"in a?a.length:void 0;return 0!=a};
export const scene=function(a){a=v(a)?a:document.getElementById("twge-default");var b={element:a};(null!=a?a:{}).innerHTML="";document.addEventListener("keydown",function(c){return k.push(c)});a.focus();a=null!=b?b:{};a.add=function(c){var d=null!=b&&"element"in b?b.element:void 0;c=null!=c&&"element"in c?c.element:void 0;return d.appendChild.call(d,c)};return a};