export const $APP = {};
export const shadow$provide = {};
export const $jscomp = {};
var C=function(a,b){a=a.split(".");var c=B;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}:c[d]=b},e=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},f=function(a){return null!=a&&!1!==a},g=function(a,b){var c=null==b?null:b.constructor;return Error(["No protocol method ",a," defined for type ",f(f(c)?c.v:c)?c.u:e(b),": ",b].join(""))},k=
function(){var a=h;if(null!=a&&null!=a.i)a=a.i(a);else{var b=k[e(null==a?null:a)];if(null!=b)a=b.j?b.j(a):b.call(null,a);else if(b=k._,null!=b)a=b.j?b.j(a):b.call(null,a);else throw g("IDeref.-deref",a);}return a},l=function(a){if(null!=a&&null!=a.m)a.m(a,!0);else{var b=l[e(null==a?null:a)];if(null!=b)b.g?b.g(a,!0):b.call(null,a,!0);else if(b=l._,null!=b)b.g?b.g(a,!0):b.call(null,a,!0);else throw g("IVolatile.-vreset!",a);}},m=function(){this.state=!1},n=function(a){this.f=a;this.value=null},p=function(a){if(null!=
a&&null!=a.o)a=a.o(a,null);else{var b=p[e(null==a?null:a)];if(null!=b)a=b.g?b.g(a,null):b.call(null,a,null);else if(b=p._,null!=b)a=b.g?b.g(a,null):b.call(null,a,null);else throw g("ICompletable.-resolve!",a);}return a},q=function(a,b,c){if(null!=a&&null!=a.s)a.s(a,b,c);else{var d=q[e(null==a?null:a)];if(null!=d)d.l?d.l(a,b,c):d.call(null,a,b,c);else if(d=q._,null!=d)d.l?d.l(a,b,c):d.call(null,a,b,c);else throw g("IScheduler.-schedule!",a);}},r=function(a,b){var c=h instanceof n?k():h;q(c,a,b)},t=
function(a){this.state=a},u=function(){},v=function(){return new u},y=function(){var a={},b=new w(function(c,d){a.resolve=c;return a.reject=d});b.A=x;b.o=function(c,d){return a.resolve(d)};b.B=function(c,d){return a.reject(d)};return b},z=function(a){var b=y();r(a,function(){return p(b)});return b},A=function(a){return z(a)};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var B=globalThis;var x={};m.prototype.m=function(a,b){return this.state=b};m.prototype.i=function(){return this.state};n.prototype.i=function(){f(this.f)&&(this.value=this.f.h?this.f.h():this.f.call(null),this.f=null);return this.value};var h=new n(function(){return v.h?v.h():v.call(null)});u.prototype.s=function(a,b,c){var d=new m,F=setTimeout(function(){try{return c.h?c.h():c.call(null)}finally{l(d)}},b);return new t({done:d,cancelled:!1,"cancel-fn":function(){return clearTimeout(F)}})};var w=Promise;C("twge.timeout",A);C("twge.goober",function(){return"goober"});export const timeout=A;