export const $APP = {};
export const shadow$provide = {};
export const $jscomp = {};
shadow$provide[0]=function(pa,qa,ra,x){function A(b,a){for(var c in a)b[c]=a[c];return b}function O(b,a,c){var e,g,f,k={};for(f in a)"key"==f?e=a[f]:"ref"==f?g=a[f]:k[f]=a[f];if(2<arguments.length&&(k.children=3<arguments.length?H.call(arguments,2):c),"function"==typeof b&&null!=b.defaultProps)for(f in b.defaultProps)void 0===k[f]&&(k[f]=b.defaultProps[f]);return C(b,k,e,g,null)}function C(b,a,c,e,g){b={type:b,props:a,key:c,ref:e,__k:null,__:null,__b:0,__e:null,__d:void 0,__c:null,__h:null,constructor:void 0,
__v:null==g?++ja:g};return null==g&&null!=u.vnode&&u.vnode(b),b}function D(b){return b.children}function E(b,a){this.props=b;this.context=a}function F(b,a){if(null==a)return b.__?F(b.__,b.__.__k.indexOf(b)+1):null;for(var c;a<b.__k.length;a++)if(null!=(c=b.__k[a])&&null!=c.__e)return c.__e;return"function"==typeof b.type?F(b):null}function S(b){var a,c;if(null!=(b=b.__)&&null!=b.__c){b.__e=b.__c.base=null;for(a=0;a<b.__k.length;a++)if(null!=(c=b.__k[a])&&null!=c.__e){b.__e=b.__c.base=c.__e;break}return S(b)}}
function P(b){(!b.__d&&(b.__d=!0)&&B.push(b)&&!I.__r++||T!==u.debounceRendering)&&((T=u.debounceRendering)||ka)(I)}function I(){var b,a,c,e,g,f,k,p;for(B.sort(U);b=B.shift();)b.__d&&(a=B.length,e=void 0,g=void 0,k=(f=(c=b).__v).__e,(p=c.__P)&&(e=[],(g=A({},f)).__v=f.__v+1,Q(p,f,g,c.__n,void 0!==p.ownerSVGElement,null!=f.__h?[k]:null,e,null==k?F(f):k,f.__h),V(e,f),f.__e!=k&&S(f)),B.length>a&&B.sort(U));I.__r=0}function W(b,a,c,e,g,f,k,p,m,r){var d,n,l,h,z,v,t=e&&e.__k||X,q=t.length;c.__k=[];for(d=
0;d<a.length;d++)if(null!=(h=c.__k[d]=null==(h=a[d])||"boolean"==typeof h||"function"==typeof h?null:"string"==typeof h||"number"==typeof h||"bigint"==typeof h?C(null,h,null,null,h):Array.isArray(h)?C(D,{children:h},null,null,null):0<h.__b?C(h.type,h.props,h.key,h.ref?h.ref:null,h.__v):h)){if(h.__=c,h.__b=c.__b+1,null===(l=t[d])||l&&h.key==l.key&&h.type===l.type)t[d]=void 0;else for(n=0;n<q;n++){if((l=t[n])&&h.key==l.key&&h.type===l.type){t[n]=void 0;break}l=null}Q(b,h,l=l||J,g,f,k,p,m,r);var w=h.__e;
(n=h.ref)&&l.ref!=n&&(v||(v=[]),l.ref&&v.push(l.ref,null,h),v.push(n,h.__c||w,h));null!=w?(null==z&&(z=w),"function"==typeof h.type&&h.__k===l.__k?h.__d=m=Y(h,m,b):m=Z(b,h,l,t,w,m),"function"==typeof c.type&&(c.__d=m)):m&&l.__e==m&&m.parentNode!=b&&(m=F(l))}c.__e=z;for(d=q;d--;)null!=t[d]&&("function"==typeof c.type&&null!=t[d].__e&&t[d].__e==c.__d&&(c.__d=aa(e).nextSibling),ba(t[d],t[d]));if(v)for(d=0;d<v.length;d++)ca(v[d],v[++d],v[++d])}function Y(b,a,c){for(var e,g=b.__k,f=0;g&&f<g.length;f++)(e=
g[f])&&(e.__=b,a="function"==typeof e.type?Y(e,a,c):Z(c,e,e,g,e.__e,a));return a}function Z(b,a,c,e,g,f){if(void 0!==a.__d){var k=a.__d;a.__d=void 0}else if(null==c||g!=f||null==g.parentNode)a:if(null==f||f.parentNode!==b)b.appendChild(g),k=null;else{a=f;for(c=0;(a=a.nextSibling)&&c<e.length;c+=1)if(a==g)break a;b.insertBefore(g,f);k=f}return void 0!==k?k:g.nextSibling}function aa(b){var a,c,e;if(null==b.type||"string"==typeof b.type)return b.__e;if(b.__k)for(a=b.__k.length-1;0<=a;a--)if((c=b.__k[a])&&
(e=aa(c)))return e;return null}function da(b,a,c){"-"===a[0]?b.setProperty(a,null==c?"":c):b[a]=null==c?"":"number"!=typeof c||la.test(a)?c:c+"px"}function K(b,a,c,e,g){a:if("style"===a)if("string"==typeof c)b.style.cssText=c;else{if("string"==typeof e&&(b.style.cssText=e=""),e)for(a in e)c&&a in c||da(b.style,a,"");if(c)for(a in c)e&&c[a]===e[a]||da(b.style,a,c[a])}else if("o"===a[0]&&"n"===a[1])g=a!==(a=a.replace(/Capture$/,"")),a=a.toLowerCase()in b?a.toLowerCase().slice(2):a.slice(2),b.l||(b.l=
{}),(b.l[a+g]=c)?e||b.addEventListener(a,g?ea:fa,g):b.removeEventListener(a,g?ea:fa,g);else if("dangerouslySetInnerHTML"!==a){if(g)a=a.replace(/xlink(H|:h)/,"h").replace(/sName$/,"s");else if("width"!==a&&"height"!==a&&"href"!==a&&"list"!==a&&"form"!==a&&"tabIndex"!==a&&"download"!==a&&a in b)try{b[a]=null==c?"":c;break a}catch(f){}"function"==typeof c||(null==c||!1===c&&"-"!==a[4]?b.removeAttribute(a):b.setAttribute(a,c))}}function fa(b){return this.l[b.type+!1](u.event?u.event(b):b)}function ea(b){return this.l[b.type+
!0](u.event?u.event(b):b)}function Q(b,a,c,e,g,f,k,p,m){var r,d,n,l,h,z,v,t,q,w,L,G,ha,M,y=a.type;if(void 0!==a.constructor)return null;null!=c.__h&&(m=c.__h,p=a.__e=c.__e,a.__h=null,f=[p]);(r=u.__b)&&r(a);try{a:if("function"==typeof y){if(t=a.props,q=(r=y.contextType)&&e[r.__c],w=r?q?q.props.value:r.__:e,c.__c?v=(d=a.__c=c.__c).__=d.__E:("prototype"in y&&y.prototype.render?a.__c=d=new y(t,w):(a.__c=d=new E(t,w),d.constructor=y,d.render=ma),q&&q.sub(d),d.props=t,d.state||(d.state={}),d.context=w,
d.__n=e,n=d.__d=!0,d.__h=[],d._sb=[]),null==d.__s&&(d.__s=d.state),null!=y.getDerivedStateFromProps&&(d.__s==d.state&&(d.__s=A({},d.__s)),A(d.__s,y.getDerivedStateFromProps(t,d.__s))),l=d.props,h=d.state,d.__v=a,n)null==y.getDerivedStateFromProps&&null!=d.componentWillMount&&d.componentWillMount(),null!=d.componentDidMount&&d.__h.push(d.componentDidMount);else{if(null==y.getDerivedStateFromProps&&t!==l&&null!=d.componentWillReceiveProps&&d.componentWillReceiveProps(t,w),!d.__e&&null!=d.shouldComponentUpdate&&
!1===d.shouldComponentUpdate(t,d.__s,w)||a.__v===c.__v){a.__v!==c.__v&&(d.props=t,d.state=d.__s,d.__d=!1);d.__e=!1;a.__e=c.__e;a.__k=c.__k;a.__k.forEach(function(N){N&&(N.__=a)});for(L=0;L<d._sb.length;L++)d.__h.push(d._sb[L]);d._sb=[];d.__h.length&&k.push(d);break a}null!=d.componentWillUpdate&&d.componentWillUpdate(t,d.__s,w);null!=d.componentDidUpdate&&d.__h.push(function(){d.componentDidUpdate(l,h,z)})}if(d.context=w,d.props=t,d.__P=b,G=u.__r,ha=0,"prototype"in y&&y.prototype.render){d.state=
d.__s;d.__d=!1;G&&G(a);r=d.render(d.props,d.state,d.context);for(M=0;M<d._sb.length;M++)d.__h.push(d._sb[M]);d._sb=[]}else{do d.__d=!1,G&&G(a),r=d.render(d.props,d.state,d.context),d.state=d.__s;while(d.__d&&25>++ha)}d.state=d.__s;null!=d.getChildContext&&(e=A(A({},e),d.getChildContext()));n||null==d.getSnapshotBeforeUpdate||(z=d.getSnapshotBeforeUpdate(l,h));var R=null!=r&&r.type===D&&null==r.key?r.props.children:r;W(b,Array.isArray(R)?R:[R],a,c,e,g,f,k,p,m);d.base=a.__e;a.__h=null;d.__h.length&&
k.push(d);v&&(d.__E=d.__=null);d.__e=!1}else null==f&&a.__v===c.__v?(a.__k=c.__k,a.__e=c.__e):a.__e=na(c.__e,a,c,e,g,f,k,m);(r=u.diffed)&&r(a)}catch(N){a.__v=null,(m||null!=f)&&(a.__e=p,a.__h=!!m,f[f.indexOf(p)]=null),u.__e(N,a,c)}}function V(b,a){u.__c&&u.__c(a,b);b.some(function(c){try{b=c.__h,c.__h=[],b.some(function(e){e.call(c)})}catch(e){u.__e(e,c.__v)}})}function na(b,a,c,e,g,f,k,p){var m,r,d=c.props,n=a.props,l=a.type,h=0;if("svg"===l&&(g=!0),null!=f)for(;h<f.length;h++)if((m=f[h])&&"setAttribute"in
m==!!l&&(l?m.localName===l:3===m.nodeType)){b=m;f[h]=null;break}if(null==b){if(null===l)return document.createTextNode(n);b=g?document.createElementNS("http://www.w3.org/2000/svg",l):document.createElement(l,n.is&&n);f=null;p=!1}if(null===l)d===n||p&&b.data===n||(b.data=n);else{if(f=f&&H.call(b.childNodes),r=(d=c.props||J).dangerouslySetInnerHTML,m=n.dangerouslySetInnerHTML,!p){if(null!=f)for(d={},h=0;h<b.attributes.length;h++)d[b.attributes[h].name]=b.attributes[h].value;(m||r)&&(m&&(r&&m.__html==
r.__html||m.__html===b.innerHTML)||(b.innerHTML=m&&m.__html||""))}r=b;var z=d,v=g,t=p,q;for(q in z)"children"===q||"key"===q||q in n||K(r,q,null,z[q],v);for(q in n)t&&"function"!=typeof n[q]||"children"===q||"key"===q||"value"===q||"checked"===q||z[q]===n[q]||K(r,q,n[q],z[q],v);if(m)a.__k=[];else if(h=a.props.children,W(b,Array.isArray(h)?h:[h],a,c,e,g&&"foreignObject"!==l,f,k,f?f[0]:c.__k&&F(c,0),p),null!=f)for(h=f.length;h--;)null!=f[h]&&(a=f[h],(c=a.parentNode)&&c.removeChild(a));p||("value"in
n&&void 0!==(h=n.value)&&(h!==b.value||"progress"===l&&!h||"option"===l&&h!==d.value)&&K(b,"value",h,d.value,!1),"checked"in n&&void 0!==(h=n.checked)&&h!==b.checked&&K(b,"checked",h,d.checked,!1))}return b}function ca(b,a,c){try{"function"==typeof b?b(a):b.current=a}catch(e){u.__e(e,c)}}function ba(b,a,c){var e,g;if(u.unmount&&u.unmount(b),(e=b.ref)&&(e.current&&e.current!==b.__e||ca(e,null,a)),null!=(e=b.__c)){if(e.componentWillUnmount)try{e.componentWillUnmount()}catch(f){u.__e(f,a)}e.base=e.__P=
null;b.__c=void 0}if(e=b.__k)for(g=0;g<e.length;g++)e[g]&&ba(e[g],a,c||"function"!=typeof b.type);c||null==b.__e||(a=b.__e,(c=a.parentNode)&&c.removeChild(a));b.__=b.__e=b.__d=void 0}function ma(b,a,c){return this.constructor(b,c)}function ia(b,a,c){var e;u.__&&u.__(b,a);var g=(e="function"==typeof c)?null:c&&c.__k||a.__k;var f=[];Q(a,b=(!e&&c||a).__k=O(D,null,[b]),g||J,J,void 0!==a.ownerSVGElement,!e&&c?[c]:g?null:a.firstChild?H.call(a.childNodes):null,f,!e&&c?c:g?g.__e:a.firstChild,e);V(f,b)}var T,
J={},X=[],la=/acit|ex(?:s|g|n|p|$)|rph|grid|ows|mnc|ntw|ine[ch]|zoo|^ord|itera/i;var H=X.slice;var u={__e:function(b,a,c,e){for(var g,f,k;a=a.__;)if((g=a.__c)&&!g.__)try{if((f=g.constructor)&&null!=f.getDerivedStateFromError&&(g.setState(f.getDerivedStateFromError(b)),k=g.__d),null!=g.componentDidCatch&&(g.componentDidCatch(b,e||{}),k=g.__d),k)return g.__E=g}catch(p){b=p}throw b;}};var ja=0;E.prototype.setState=function(b,a){var c=null!=this.__s&&this.__s!==this.state?this.__s:this.__s=A({},this.state);
"function"==typeof b&&(b=b(A({},c),this.props));b&&A(c,b);null!=b&&this.__v&&(a&&this._sb.push(a),P(this))};E.prototype.forceUpdate=function(b){this.__v&&(this.__e=!0,b&&this.__h.push(b),P(this))};E.prototype.render=D;var B=[];var ka="function"==typeof Promise?Promise.prototype.then.bind(Promise.resolve()):setTimeout;var U=function(b,a){return b.__v.__b-a.__v.__b};var oa=I.__r=0;x.Component=E;x.Fragment=D;x.cloneElement=function(b,a,c){var e,g,f,k=A({},b.props);for(f in a)"key"==f?e=a[f]:"ref"==f?
g=a[f]:k[f]=a[f];return 2<arguments.length&&(k.children=3<arguments.length?H.call(arguments,2):c),C(b.type,k,e||b.key,g||b.ref,null)};x.createContext=function(b,a){var c={__c:a="__cC"+oa++,__:b,Consumer:function(e,g){return e.children(g)},Provider:function(e){var g,f;return this.getChildContext||(g=[],(f={})[a]=this,this.getChildContext=function(){return f},this.shouldComponentUpdate=function(k){this.props.value!==k.value&&g.some(function(p){p.__e=!0;P(p)})},this.sub=function(k){g.push(k);var p=k.componentWillUnmount;
k.componentWillUnmount=function(){g.splice(g.indexOf(k),1);p&&p.call(k)}}),e.children}};return c.Provider.__=c.Consumer.contextType=c};x.createElement=O;x.createRef=function(){return{current:null}};x.h=O;x.hydrate=function e(a,c){ia(a,c,e)};x.isValidElement=function(a){return null!=a&&void 0===a.constructor};x.options=u;x.render=ia;x.toChildArray=function g(c,e){return e=e||[],null==c||"boolean"==typeof c||(Array.isArray(c)?c.some(function(f){g(f,e)}):e.push(c)),e}};
var C=function(a,b){a=a.split(".");var c=B;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)a.length||void 0===b?c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}:c[d]=b},e=function(a){var b=typeof a;return"object"!=b?b:a?Array.isArray(a)?"array":b:"null"},f=function(a){return null!=a&&!1!==a},g=function(a,b){var c=null==b?null:b.constructor;return Error(["No protocol method ",a," defined for type ",f(f(c)?c.v:c)?c.u:e(b),": ",b].join(""))},k=
function(){var a=h;if(null!=a&&null!=a.i)a=a.i(a);else{var b=k[e(null==a?null:a)];if(null!=b)a=b.j?b.j(a):b.call(null,a);else if(b=k._,null!=b)a=b.j?b.j(a):b.call(null,a);else throw g("IDeref.-deref",a);}return a},l=function(a){if(null!=a&&null!=a.m)a.m(a,!0);else{var b=l[e(null==a?null:a)];if(null!=b)b.g?b.g(a,!0):b.call(null,a,!0);else if(b=l._,null!=b)b.g?b.g(a,!0):b.call(null,a,!0);else throw g("IVolatile.-vreset!",a);}},m=function(){this.state=!1},n=function(a){this.f=a;this.value=null},p=function(a){if(null!=
a&&null!=a.o)a=a.o(a,null);else{var b=p[e(null==a?null:a)];if(null!=b)a=b.g?b.g(a,null):b.call(null,a,null);else if(b=p._,null!=b)a=b.g?b.g(a,null):b.call(null,a,null);else throw g("ICompletable.-resolve!",a);}return a},q=function(a,b,c){if(null!=a&&null!=a.s)a.s(a,b,c);else{var d=q[e(null==a?null:a)];if(null!=d)d.D?d.D(a,b,c):d.call(null,a,b,c);else if(d=q._,null!=d)d.D?d.D(a,b,c):d.call(null,a,b,c);else throw g("IScheduler.-schedule!",a);}},r=function(a,b){var c=h instanceof n?k():h;q(c,a,b)},t=
function(a){this.state=a},u=function(){},v=function(){return new u},y=function(){var a={},b=new w(function(c,d){a.resolve=c;return a.reject=d});b.A=x;b.o=function(c,d){return a.resolve(d)};b.B=function(c,d){return a.reject(d)};return b},z=function(a){var b=y();r(a,function(){return p(b)});return b},I=function(a,b){var c=D[a];if(void 0!==c)return c;try{G.push(a);var d=H[a],F=shadow$provide[a];if(void 0===d){if(void 0===F)throw"Module not provided: "+a;d={exports:{}};H[a]=d}if(F){delete shadow$provide[a];
try{F.call(d,B,I,d,d.exports)}catch(M){throw console.warn("shadow-cljs - failed to load",a),M;}if(b){var E=b.globals;if(E)for(a=0;a<E.length;a++)window[E[a]]=d.exports}}}finally{G.pop()}return d.exports},A=function(a){return z(a)},K=function(){var a=J.h("h1",null,"Hello"),b=document.getElementById("twge-default");b.innerHTML="";return J.render(a,b)};/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var B=globalThis;var x={};m.prototype.m=function(a,b){return this.state=b};m.prototype.i=function(){return this.state};n.prototype.i=function(){f(this.f)&&(this.value=this.f.C?this.f.C():this.f.call(null),this.f=null);return this.value};var h=new n(function(){return v.C?v.C():v.call(null)});u.prototype.s=function(a,b,c){var d=new m,F=setTimeout(function(){try{return c.C?c.C():c.call(null)}finally{l(d)}},b);return new t({done:d,cancelled:!1,"cancel-fn":function(){return clearTimeout(F)}})};var w=Promise;var H={},D={},G=[];I.cache={};I.resolve=function(a){return a};var J;J=I(0,{});C("twge.timeout",A);C("twge.draw",K);export default{}.F;export const timeout=A;export const draw=K;